Update crates.md
mxz7/nypsi-docs pull request #3
Opened 2024-06-30 14:49 UTC by konal1019

2024-06-30 15:10 UTC, mxz7 requested changes
everything gotta be lowercase!

2024-06-30 15:10 UTC, mxz7 commented on economy/crates.md
> +You can use the `$use <name of crate> <amount>` commmand to open specific number of a specific crate.
lowercase

2024-06-30 15:10 UTC, mxz7 commented on economy/crates.md
> +you can easily obtain vote crates by voting for nypsi with `$vote`. You can also get crates from
lowercase

2024-07-03 16:27 UTC, mxz7 commented
Are you going to rectify the issues?

2024-07-03 17:21 UTC, konal1019 commented on economy/crates.md
> +you can easily obtain vote crates by voting for nypsi with `$vote`. You can also get crates from
Ok I will fix it

2024-07-04 11:12 UTC, mxz7 commented
You must resolve the conflicts

2024-07-04 17:03 UTC, mxz7 requested changes

2024-07-04 17:03 UTC, mxz7 commented on economy/achievements.md
> +this will show the details of the achievement as well as the rewards you get for completing them. there are currently 34 unique qchievements in nypsi with each having 5 levels amounting to a total of
for achievements specifically i'd ask you tell people to use the slash (/) command versions. it's easier for achievements, especially the find view command

2024-07-05 12:11 UTC, merged